//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UsingWebBrowserLib.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("UsingWebBrowserLib.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to function log() {
        ///    document.getElementById(&apos;results&apos;).innerText = &apos;&apos;;
        ///
        ///    Array.prototype.forEach.call(arguments, function (msg) {
        ///        if (msg instanceof Error) {
        ///            msg = &quot;Error: &quot; + msg.message;
        ///        }
        ///        else if (typeof msg !== &apos;string&apos;) {
        ///            msg = JSON.stringify(msg, null, 2);
        ///        }
        ///        document.getElementById(&apos;results&apos;).innerHTML += msg + &apos;\r\n&apos;;
        ///    });
        ///}
        ///
        ///document.getElementById(&quot;login&quot;).addEventListener(&quot;click&quot;, login, false);
        ///document.getElementById(&quot;api&quot;).a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string app_js {
            get {
                return ResourceManager.GetString("app_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;script src=&quot;oidc-client.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script&gt;
        ///        new Oidc.UserManager().signinRedirectCallback().then(function () {
        ///            window.location = &quot;index.html&quot;;
        ///        }).catch(function (e) {
        ///            console.error(e);
        ///        });
        ///    &lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string callback_html {
            get {
                return ResourceManager.GetString("callback_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html&gt;
        ///&lt;head&gt;
        ///    &lt;meta charset=&quot;utf-8&quot; /&gt;
        ///    &lt;title&gt;&lt;/title&gt;
        ///&lt;/head&gt;
        ///&lt;body&gt;
        ///    &lt;button id=&quot;login&quot; style=&quot;display: none;&quot;&gt;Login&lt;/button&gt;
        ///    &lt;button id=&quot;api&quot;&gt;Call API&lt;/button&gt;
        ///    &lt;button id=&quot;logout&quot;&gt;Logout&lt;/button&gt;
        ///    &lt;pre id=&quot;results&quot;&gt;&lt;/pre&gt;
        ///    &lt;script src=&quot;oidc-client.js&quot;&gt;&lt;/script&gt;
        ///    &lt;script src=&quot;app.js&quot;&gt;&lt;/script&gt;
        ///&lt;/body&gt;
        ///&lt;/html&gt;.
        /// </summary>
        public static string index_html {
            get {
                return ResourceManager.GetString("index_html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*! jQuery v3.2.1 | (c) JS Foundation and other contributors | jquery.org/license */
        ///!function(a,b){&quot;use strict&quot;;&quot;object&quot;==typeof module&amp;&amp;&quot;object&quot;==typeof module.exports?module.exports=a.document?b(a,!0):function(a){if(!a.document)throw new Error(&quot;jQuery requires a window with a document&quot;);return b(a)}:b(a)}(&quot;undefined&quot;!=typeof window?window:this,function(a,b){&quot;use strict&quot;;var c=[],d=a.document,e=Object.getPrototypeOf,f=c.slice,g=c.concat,h=c.push,i=c.indexOf,j={},k=j.toString,l=j.hasOwnProperty,m=l.toStrin [rest of string was truncated]&quot;;.
        /// </summary>
        public static string jquery_3_2_1_min_js {
            get {
                return ResourceManager.GetString("jquery_3_2_1_min_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var Oidc =
        ////******/ (function (modules) { // webpackBootstrap
        ////******/ 	// The module cache
        ////******/ 	var installedModules = {};
        ////******/
        ////******/ 	// The require function
        ////******/ 	function __webpack_require__(moduleId) {
        ////******/
        ////******/ 		// Check if module is in cache
        ////******/ 		if (installedModules[moduleId])
        ////******/ 			return installedModules[moduleId].exports;
        ////******/
        ////******/ 		// Create a new module (and put it into the cache)
        ////******/ 		var module = installedModules[moduleId] = {
        ////******/ 			ex [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oidc_client_js {
            get {
                return ResourceManager.GetString("oidc_client_js", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to var Oidc=function(t){function e(r){if(n[r])return n[r].exports;var i=n[r]={exports:{},id:r,loaded:!1};return t[r].call(i.exports,i,i.exports,e),i.loaded=!0,i.exports}var n={};return e.m=t,e.c=n,e.p=&quot;&quot;,e(0)}([function(t,e,n){n(1),t.exports=n(326)},function(t,e,n){(function(t){&quot;use strict&quot;;function e(t,e,n){t[e]||Object[r](t,e,{writable:!0,configurable:!0,value:n})}if(n(2),n(322),n(323),t._babelPolyfill)throw new Error(&quot;only one instance of babel-polyfill is allowed&quot;);t._babelPolyfill=!0;var r=&quot;defineProperty [rest of string was truncated]&quot;;.
        /// </summary>
        public static string oidc_client_min_js {
            get {
                return ResourceManager.GetString("oidc_client_min_js", resourceCulture);
            }
        }
    }
}
